### ISSUE TITLE
Error running 'objdump -p /usr/lib/x86_64-linux-gnu/libpython3.8.so.1':

### ISSUE THREAD

**Issue by EB57PzUhYmQsMm** [NurTasin/botnet#2]
`sh ./make_executable.sh`
Error running 'objdump -p /usr/lib/x86_64-linux-gnu/libpython3.8.so.1':
[Errno 2] No such file or directory: 'objdump'
Error: Executing command failed!

I have no idea honestly

**Comment by EB57PzUhYmQsMm** [comment]
I did make a bat file on windows
I was looking around github and forgot that I already tested this haha
but might as well put it here

**Comment by EB57PzUhYmQsMm** [comment]
UBUNTU 20.04 LTS
Linode

**Comment by NurTasin** [comment]
I ran these commands:
```bash
git clone https://github.com/NurTasin/botnet.git
cd botnet
pip3 install -r requirements.txt
sh make_executable.sh
```
and it created an executable called `networkmanager` in `./bin` directory.
I haven't received any kind of error what so ever. 
#### Device Configuration:
OS: `Ubuntu 20.04.2 LTS`
Kernel: `5.4.0-80-generic`

#### NOTE: I AM CURRENTLY FOCUSING ON WINDOWS SIDE. I HADN'T COMPILED THIS IN LINUX BEFORE. ANY KIND OF CONTRIBUTIONS ARE WELCOMED THOUGH. :-)
